//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SecretSanta.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SecretSanta.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 20 euro.
        /// </summary>
        internal static string amount {
            get {
                return ResourceManager.GetString("amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to false.
        /// </summary>
        internal static string debug {
            get {
                return ResourceManager.GetString("debug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Babbo Natale &lt;babbo.natale@itattitude.eu&gt;.
        /// </summary>
        internal static string displayFrom {
            get {
                return ResourceManager.GetString("displayFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to smtpout.europe.secureserver.net.
        /// </summary>
        internal static string hostname {
            get {
                return ResourceManager.GetString("hostname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \\SecretSanta.
        /// </summary>
        internal static string logFolder {
            get {
                return ResourceManager.GetString("logFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ciao $name$!
        ///
        ///Purtroppo ho la slitta a riparare, e non sono sicuro di riuscire a consegnare tutti i regali in tempo... mi faresti un favore? 
        ///Faresti un regalo a $nameTo$ $surnameTo$?
        ///
        ///Mi raccomando, cerca di capire cosa gli piace ma non farglielo sapere! Porta il regalo alla cena di natale, il 16, che ve li scambierete li&apos; ;) 
        ///
        ///Visto oltretutto che capisco perfettamente che non tutti hanno una fabbrica di elfetti sch... volontari a costruire i regali ho pensato che sarebbe carino tenere il regalo in [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string messageBody {
            get {
                return ResourceManager.GetString("messageBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Felizian0.
        /// </summary>
        internal static string password {
            get {
                return ResourceManager.GetString("password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3535.
        /// </summary>
        internal static string port {
            get {
                return ResourceManager.GetString("port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to babbo.natale@itattitude.eu.
        /// </summary>
        internal static string sender {
            get {
                return ResourceManager.GetString("sender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to babbo.natale@itattitude.eu.
        /// </summary>
        internal static string username {
            get {
                return ResourceManager.GetString("username", resourceCulture);
            }
        }
    }
}
